---
title: Responsible Prediction Making of COVID-19 Mortality
#subtitle: Landing Page
#date: "`r Sys.Date()`"
output: rmdformats::html_docco
---

<!-- Place this tag in your head or just before your close body tag. -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<style type="text/css">
.main-container {
  max-width: 1150px;
}
@media (min-width: 992px) {
  .col-md-offset-1 {
    margin-left: 0%;
  }
  .col-md-10 {
    width: 100%;
}
}

h1.title {
    text-transform: none !important;
}

.r2d3 {
  position: relative !important;
}
</style>

## Paper

Baniecki, H. and Biecek, P. **Responsible Prediction Making of COVID-19 Mortality (Student Abstract)** TBA

Available at TBA

## Abstract 

*For high-stakes prediction making, the Responsible Artificial Intelligence (RAI) is more important than ever. It builds upon Explainable Artificial Intelligence (XAI) to advance the efforts in providing fairness, model explainability, and accountability to the AI systems. During the literature review of COVID-19 related prognosis and diagnosis, we found out that most of the predictive models are not faithful to the RAI principles, which can lead to biassed results and wrong reasoning. To solve this problem, we show how novel XAI techniques boost transparency, reproducibility and quality of models.* 

## Dashboard <a class="github-button" href="https://github.com/MI2DataLab/rai-covid" data-color-scheme="no-preference: light; light: light; dark: dark;" data-size="large" data-show-count="true" aria-label="Star MI2DataLab/rai-covid on GitHub">rai-covid</a>

```{r echo=FALSE, warning=FALSE}
library(reticulate)
explainer <- py_load_object("xgboost-explainer.pkl", pickle = "pickle")

local_obs <- explainer$data[c(213, 79, 105, 129, 167, 187, 198, 270, 289, 299, 307, 329, 330, 340, 365), ]
rownames(local_obs) <- paste("id:", rownames(local_obs),
                             "| pred:", 
                             round(explainer$predict(local_obs), 4))

library(modelStudio)
set.seed(0)
modelStudio(explainer,
            new_observation = local_obs,
            B = factorial(dim(explainer$data)[2]),
            license = "LICENSE")
```

## Citation

To cite this work, use the following BibTeX entry:

```
TBA
```

Preliminary code for this work is available at https://github.com/hbaniecki/Pre-Surv-COVID-19